export const CHANGE_CARD_NUMBER_VALUE = 'CHANGE_CARD_NUMBER_VALUE';
export const CHANGE_CARD_NAME_VALUE = 'CHANGE_CARD_NAME_VALUE';
export const CHANGE_CARD_VALIDATE_VALUE = 'CHANGE_CARD_VALIDATE_VALUE';
export const CHANGE_CARD_CVV_VALUE = 'CHANGE_CARD_CVV_VALUE';
export const CHANGE_CARD_CVV_ACTIVE = 'CHANGE_CARD_CVV_ACTIVE';